#   <<VAN DEEP>> PRODUCED BY RICHARD余世炅
print("===================================================================================================")
print("===================================================================================================")
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print("++++++++++++++++++++++++++\        /     /\         /\        /++++++++++++++++++++++++++++++++++++")
print("+++++++++++++++++++++++++++\      /     /  \       /  \      /+++++++++++++++++++++++++++++++++++++")
print("++++++++++++++++++++++++++++\    /     /----\     /    \    /++++++++++++++++++++++++++++++++++++++")
print("+++++++++++++++++++++++++++++\  /     /      \   /      \  /+++++++++++++++++++++++++++++++++++++++")
print("++++++++++++++++++++++++++++++\/     /        \ /        \/++++++++++++++++++++++++++++++++++++++++")
print("+++++++++++++++++++|----\    |----  |----   |---\++++++++++++++++++++++++++++++++++++++++++++++++++")
print("+++++++++++++++++++|     |   |      |       |   |++++++++++++++++++++++++++++++++++++++++++++++++++")
print("+++++++++++++++++++|     |   |----  |----   |---/++++++++++++++++++++++++++++++++++++++++++++++++++") 
print("+++++++++++++++++++|     |   |      |       |    ++++++++++++++++++++++++++++++++++++++++++++++++++")
print("+++++++++++++++++++|----/    |----  |----   |    ++++++++++++++++++++++++++++++++++++++++++++++++++")
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print("++++++++++++++++++++++++++++++++++++----BY:RICHARD-----++++++++++++++++++++++++++++++++++++++++++++")
print("_______________________________________WORKING TEAM : BRICONIS_____________________________________")
print("_________________________________________________________________________________1.1.2_____________")
print("===================================================================================================")
print("===================================================================================================")
print("                                             ")
print("    ")
input("                             PRESS ENTER TO BIGIN THIS GAME.")
print("                       REMEMBER TO PRESS ENTER TO CONTINUE THE STORY")
print("                    AND DEFINRTELY INPUT THE WORDS THAT AFFECT THIS GAME")
PASSWORD=input("               NOW PLEASE GIVE ME YOUR PASSWORD:")
print("                         SO YOUR PASSWORD IS",PASSWORD)
print("     ")
NUM0=input("                              WELCOME TO VAN")
if NUM0=="DEEP DARK FANTASY":
    print("                 乖乖站好！！！！BBBOOOOOOOOOOOOOOOOOOOOOKI!!!!!!!")
else:
    print("      ")
USERNAME=input("               CAN YOU TELL ME YOUR NAME AGAIN:")
if USERNAME=="DIO":
    print("              KO NO DIO  DA")
if USERNAME=="JOJO":
    print("              我不做人了，乔乔！！！！！")
else:
    print("             ok")
print("余世炅出现了————————————————————————————————————————————")
print("这次的问题是：头号玩家中，男主是在游戏中的哪里给女主表白的？请在QQ上私聊炅炅回答问题哦！！！！！！！")
input("余世炅消失了————————————————————————————————————————————")
print("___________________________________________________________________________________________________")
print("                    C    H    A    P    T    E    R        T   W   O")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
input("                                       PRESS ENTER TO START     ")
print("                CHRIS:THAT'S DANGEROUS!!!")
input("                TGR:WELL,THAT'S THE POWER OF VAN ENERGY")
input("                TGR:THAT'S WHY I WANT TO STOP BRUCE.")
print("                TONY:BRUCE?")
input("                TGR:WATCH THIS VIDEO.........")
print("                    大家好呀，我是今天的播报员----KATE。请看今天的新闻。")
print("   BRUCE，一个第一次被我们媒体关注的动物改造者。他拥有一种被叫做VAN的药剂。可以使动物变得更加强壮。")
print("可是，之前我们看见一只疑似被注入了VAN药剂的牛，在死亡后爆炸了。摧毁了一座楼。当时据说有个很大的巨人")
input("             从烟雾中走出。这个VAN到底是什么物质让种种科学无法解释的事件发生。")
input("                TGR:SO,I WON'T LIE TO YOU ALL GUYS.")
input("                TGR:ACTUALLY,BRUCE IS MY YOUNGER BROTHER.OUR SURNAME IS VAN")
input("                   WE FOUND A KIND OF MEDICINE THAT CAN MAKE PEOPLE OR ANIMALS STRONGER.")
input("                   HOWEVER,BRUCE WANT TO MAKE IT USED ON ANIMALS TO HAVE A WIDE VARIETY OF STRONG ANIMALS")
input("                 CHRIS:That's really dangerous.")
input("                 TONY:WE HAVE TO FIND BRUCE!")
input("                     TGR:LEEEEEEEEET'S DOOOOOOOOOOOOOOOOOOOOOOOOOO THIS.")
print("在这之后，师徒四人遇到了来自布鲁斯的第一个怪兽。。。。。。。。。。。。。。")
input("                      TGR:this is our first challenge.")
input("                      CHRIS:this monster can hit you every time you hit it.15unit/time.its hp is 80")
print("你的生命值是50")
print("  1-----强化：一回合内强化技能或平A。伤害*1.5       可以与平a一起作为一回合")
print("  2-----伤害：立刻伤害20                        不可以与平a一起作为一回合")
print("  3-----增强：此技能以后角色使用一个技能，下一个回合开始，伤害加百分之十，并且角色获得剩余HP的百分之五十的只存在一局的护盾。")
print("                                                 可以与平a一起作为一回合")
print("  4-----终结：立刻造成上回合伤害的两倍。        不可以与平a一起作为一回合")
print("A-----------       1a-1a-1a-1a-1a")
print("B-----------       2-1a-1a-2-4")
print("C-----------       3a-2-2-4-1a")
print("D-----------       3a-1a-1a-2-4")
NUM1=input("E----------       1a-1a-3a-2-4")
if NUM1=="A" or "B" or "D" or "E":
    print("             YOU DIED............START THIS CHAPTER AGAIN")
if NUM1=="C":
    print("             you got this one!!!!!!!!!!!!")
    print("                 it is dead!!!!!!!!")
    print("                first blood.......")
    print("                 TGR:good one .")
    NUM2=input("you can say thanks or normal fighting")
    if NUM2=="thanks":
        print("        TGR:you are good,really.the first time,you win.")
    if NUM2=="normal fighting":
        print("        TGR:ok       ok")
    else:
        print("         ")
    print("                 level up! LV5---->LV10")
    print("                   TGR:now,where do you want to go?")
    input("注意一下哦，这个地方炅炅可是费尽心思，故事有两个走向但是第二章的结局是一样的。")
    print("                  ",USERNAME,":well,i will go to the.............")
    NUM2=input("north or west?")
    if NUM2=="north":
        print("                      TGR:ok,let's go!")
        print("               Chris:WOW!!!!!!this is a huge mountain.")
        print("               TGR:really?you've never seen the mountains in this size?")
        print("               Chris:yeah.what about you,",USERNAME,"?")
        NUM3=input("yes or no")
        if NUM3=="yes":
            print("             Chris:alright.")
        if NUM3=="no":
            print("              Chris:richard,see?",USERNAME,"didn't see any,too.haha,is your face hurt?")
        else:
            print("            ")
        input("         TGR:now,no joking.let's go through this thing.")
        print("       ",USERNAME,":exactly.richard.")
        input("         TGR:well,this is really unlacky.a crazy......")
        input("                                                       pig?")
        print("             go get it",USERNAME)
        print("又是打怪兽的时间了呀")
        print("加油吧")
        print("           Chris:this monster is going to give himself 5hp per fight.total hp is 50")
        input("                 and hit you 20hp per fight.")
        print("  平A-----10")
        print("  1-----强化：一回合内强化技能或者平A。伤害*1.5       可以与平a一起作为一回合")
        print("  2-----伤害：立刻伤害20                        不可以与平a一起作为一回合")
        print("  3-----增强：此技能以后角色使用一个技能，下一回合开始，伤害加百分之十，并且角色获得剩余HP的百分之五十的只存在一局的护盾。")
        print("                                                 可以与平a一起作为一回合")
        print("  4-----终结：立刻造成上回合伤害的两倍。        不可以与平a一起作为一回合")
        print("A-----------------   1a-2-4-12-3a")
        print("B-----------------   12-1a-a-4-a")
        print("C-----------------   12-a-1a-4-3a")
        print("D-----------------   3a-2-1a-3a-4")
        NUM4=input("E-----------------   a-12-4-3a-4")
        if NUM4=="A":
            print("you did it!!!!!!")
            print("                    TGR:well,done.",USERNAME)
            print("                                           you are the winner!!!!!!!!!!!!!!!!")
            input("                    Chris:let's go!")
            print("====================================================================================")
            print("====================================================================================")
            print("====================================================================================")
            print("                          //-----------------------------------\\")
            print("                         //-------------------------------------\\")
            print("                        //---------------------------------------\\")
            print("                       //|       ____                            |\\          ")
            print("                         |      |    |            ______         |                  ")
            print("                         |      |    |           |      |        |              ")
            print("                         |      ~~~~~~           |      |        |     ")
            print("                         |                       |     @|        |              ")
            print("                         |                       |      |        |     ")
            print("                         |                       |      |        |       ")
            print("                         |                       ~~~~~~~~        |                                     ")
            input("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
            print("                     TGR:look at this house,let's go in there!")
            print("                     ",USERNAME,":okok!!!!!")
            input("                           level up!!!  10-->15            hp---------150")
            print("                            it is really dark here.            ")
            print("                you can only hear the sound of your steps........")
            print("                 you can see nothing .................")
            input("                                 SUDDENLY")
            input("                    you hear a really low voice from your back......")
            print("        ")
            input("                                 ???:who let you come in here.....")
            input("                                TGR:who the hell are you.")
            input("                               ???:I'M THE FATTEST LUIS.")
            input("                                  CHRIS:fattest?hahhahahahah")
            input("                                 ???:laugh............i've heard of that a lot. ")
            input("                                  they all laugh at me.....")
            input("                                  but,finally.they died,i killed them all.")
            input("                                 i'm a VANTIQUE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print("vantique:拥有van的能力的人")
            print("                                 and i am going to kill you four,toooooooooooooooooooooo!!!!!")
            print("这是第二章最后的boss。打败他吧。")
            input("                 THE FATTEST LUIS_________________hp:200    sp:30/time")
            print("  平A-----10")
#              hp=150
            print("  1-----强化：一回合内强化技能或者平A。伤害*1.5       可以与平a一起作为一回合")
            print("  2-----伤害：立刻伤害20                        不可以与平a一起作为一回合")
            print("  3-----增强：此技能以后角色使用一个技能，一回合内用的技能不重叠计算,,伤害四舍五入，下一回合开始，伤害加百分之十，并且角色获得剩余HP的百分之十的只存在一局的护盾。")
            print("                                                 可以与平a一起作为一回合")
            print("  4-----终结：立刻造成上回合伤害的两倍。        不可以与平a一起作为一回合")
            print("A----------   3a-a-a-a")
            print("B----------   2-2-1a-4-a-3a-a")
            print("C----------   3a-2-12-4-1a-4-3a-2-4")
            print("D----------   2-a-12-12-12-a")
            NUM999=input("E----------   1a-1a-4-3a-12-4-a")
            if NUM999=="A"or"B"or"D"or"E":
                print("you lose...............................................")
                print("try again")
            if NUM999=="C":
                print("you win!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
#end-----------------------------------------part----------------------------------------------------------------------------------------------------
                print("                      E   N   D      O   F      C   H   A   P   T   E   R       T   W   O")
                input("                    觉得这个游戏咋样啊，是不是有点短。没事哦，我会在以后加上一点内容的。")
                input("                    thanks!!!!!!!!!!!!!!!!!!")
                input("               炅炅还在辛苦制作中，先把这几章的大概剧情过完哈")
                input("              ok，请期待第三章哦！！！！！！！")
                input("========================================================================================================================")
                input("======================================================感谢游玩==========================================================")
                input("========================================================================================================================")
                input("                                     produced by 余世炅Richad，woking team:BRICONIS")
            
#----------------------------------------------------------------------------------
#主线一
        if NUM4=="B"or"C"or"D"or"E":
            print("you lost......................")      
#----------------------------------------------------------------------------------
#这条线以上是主线一，以下是主线二。。。。。。。。。。。。。。。。。。。。。。。。。
    if NUM2=="west":
        print("                     TGR:ok,let's go!")
        print("                      TGR:this is really a big lake.")
        NUM5=input("ok, are you going to go through it? yes or no ")
        if NUM5=="yes":
            print("                           TGR:okok")
            print("                                    LET'S GO AND FIND A BOAT")
        if NUM5=="no":
            print("                            TGR:alright")
            print("                              CHRIS:noooooooooo! let's do this!find a boat and get through!!!!!!")
        else:
            print("          ")
        print("                        TGR:look at that big fishmonster.kill it,",USERNAME)
        print("又是打怪兽的时间了呀")
        print("加油吧")
        print("           Chris:this monster is going to give himself 5hp per fight.total hp is 50")
        input("                 and hit you 20hp per fight.")
        print("  平A-----10")
        print("  1-----强化：一回合内强化技能或者平A。伤害*1.5       可以与平a一起作为一回合")
        print("  2-----伤害：立刻伤害20                        不可以与平a一起作为一回合")
        print("  3-----增强：此技能以后角色使用一个技能，下一回合开始，伤害加百分之十，并且角色获得剩余HP的百分之五十的只存在一局的护盾。")
        print("                                                 可以与平a一起作为一回合")
        print("  4-----终结：立刻造成上回合伤害的两倍。        不可以与平a一起作为一回合")
        print("A-----------------   1a-2-4-12-3a")
        print("B-----------------   12-1a-a-4-a")
        print("C-----------------   12-a-1a-4-3a")
        print("D-----------------   3a-2-1a-3a-4")
        NUM4=input("E-----------------   a-12-4-3a-4")
        if NUM4=="A":
            print("you did it!!!!!!")
            print("                    TGR:well,done.",USERNAME)
            print("                                           you are the winner!!!!!!!!!!!!!!!!")
            input("                    Chris:let's go!")  
            input("                           TGR:there is a house !")
            print("=====================================================================================================================================                              ")
            print("===================================================================================================================================== ")
            print("                                                                             |   |")
            print("                                                                             |   |")
            print("                                                                             |   |")
            print("                                                                             |   |")
            print("                                        (`~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~)                                                                       ")
            print("                                       (~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~)                   ")
            print("                                      (~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~)                               ")
            print("                                     (~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~)                    ")
            print("                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
            print("                                     |       ____        _____                              |         ")
            print("                                     |      |    |      |     |              ______         |                  ")
            print("                                     |      |    |      |     |             |      |        |")
            print("                                     |      ~~~~~~      ~~~~~~~             |      |        |     ")
            print("                                     |                                      |     @|        |              ")
            print("                                     |                                      |      |        |     ")
            print("                                     |                                      |      |        |       ")
            print("                                     |                                      ~~~~~~~~        |                                     ")
            input("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
            print("                     TGR:look at this house,let's go in there!")
            print("                     ",USERNAME,":okok!!!!!")
            input("                           level up!!!  10-->15            hp---------150")
            print("                            it is really dark here.            ")
            print("                you can only hear the sound of your steps........")
            print("                 you can see nothing .................")
            input("                                 SUDDENLY")
            input("                    you hear a really low voice from your back......")
            print("        ")
            input("                                 ???:who let you come in here.....")
            input("                                TGR:who the hell are you.")
            input("                               ???:I'M THE FATTEST LUIS.")
            input("                                  CHRIS:fattest?hahhahahahah")
            input("                                 ???:laugh............i've heard of that a lot. ")
            input("                                  they all laugh at me.....")
            input("                                  but,finally.they died,i killed them all.")
            input("                                 i'm a VANTIQUE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            print("vantique:拥有van的能力的人")
            print("                                 and i am going to kill you four,toooooooooooooooooooooo!!!!!")
            print("这是第二章最后的boss。打败他吧。")
            input("                 THE FATTEST LUIS_________________hp:200    sp:30/time")
            print("  平A-----10")
#              hp=150
            print("  1-----强化：一回合内强化技能或者平A。伤害*1.5       可以与平a一起作为一回合")
            print("  2-----伤害：立刻伤害20                        不可以与平a一起作为一回合")
            print("  3-----增强：此技能以后角色使用一个技能，一回合内用的技能不重叠计算,,伤害四舍五入，下一回合开始，伤害加百分之十，并且角色获得剩余HP的百分之十的只存在一局的护盾。")
            print("                                                 可以与平a一起作为一回合")
            print("  4-----终结：立刻造成上回合伤害的两倍。        不可以与平a一起作为一回合")
            print("A----------   3a-a-a-a")
            print("B----------   2-2-1a-4-a-3a-a")
            print("C----------   3a-2-12-4-1a-4-3a-2-4")
            print("D----------   2-a-12-12-12-a")
            NUM999=input("E----------   1a-1a-4-3a-12-4-a")
            if NUM999=="A"or"B"or"D"or"E":
                print("you lose...............................................")
                print("try again")
            if NUM999=="C":
                print("                       you win!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
                input("                                                      ")
#end part-------------------------------------------------------------------------------------------------
                print("                      E   N   D      O   F      C   H   A   P   T   E   R       T   W   O")
                input("                    觉得这个游戏咋样啊，是不是有点短。没事哦，我会在以后加上一点内容的。")
                input("                    thanks!!!!!!!!!!!!!!!!!!")
                input("               炅炅还在辛苦制作中，先把这几章的大概剧情过完哈")
                input("              ok，请期待第三章哦！！！！！！！")
                input("========================================================================================================================")
                input("======================================================感谢游玩==========================================================")
                input("========================================================================================================================")
                input("                                     produced by 余世炅Richad，woking team:BRICONIS")
#-------------------------------------------------------------------------------------------------------------------------------            
        if NUM4=="B"or"C"or"D"or"E":
            print("you lost......................")
        else:
            print("                 ")
#__________________________________________________________________________________
else:
    print("             ")





